config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get '/index', to: 'static_pages#index'
  get '/contact_us', to: 'static_pages#contact_us'
  get '/business_info', to: 'static_pages#business_info'

  get '/shades_index', to: 'shades#shades_index'
  get '/solid_shades', to: 'shades#solid_shades'
  get '/design_shades', to: 'shades#design_shades'
  get '/sports_shades', to: 'shades#sports_shades'
  get '/custom_shades', to: 'shades#custom_shades'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shades_controller.rb
class ShadesController < ApplicationController

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! HTML
%html
%head
  %title EazyShade
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  :javascript
    jQuery(function($) {
    $('.slider').sss();
    });


%body
  %nav.navbar.navbar-inverse.navbar-fixed-top
    .container
      .navbar-header
        = link_to "EazyShade", root_path, class: "navbar-brand"
      .collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.dropdown
            =link_to('#', class: 'dropdown-toggle', data: {toggle: 'dropdown'}, role: 'button') do
              Shades
              %span.caret

            %ul.dropdown-menu{"role" => "menu"}
              %li= link_to "Design", design_shades_path
              %li= link_to "Sports", sports_shades_path
              %li.divider
              %li= link_to "Custom", custom_shades_path
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Contact Us", contact_us_path

  %br
  %br
  %br

  .container

    - if flash[:notice]
      %p.alert.alert-success
        = flash[:notice]

    - if flash[:error]
      %p.alert.alert-danger
        = flash[:error]

    = yield

    %footer
      %hr
        = link_to "Home", root_path
        |
        = link_to "Shades", shades_index_path
        |
        = link_to "Contact Us", contact_us_path
        .pull-right
          Copyright @ EazyShade 2015

app/views/shades/custom_shades.html.erb
<div class="page-header">
  <h1>Custom Shades</h1>
<hr>

<div class="slider">
  <%= image_tag("redbull.jpg") %>
  <%= image_tag("gopro.jpg") %>
  <%= image_tag("apple.jpg") %>
  <%= image_tag("coke.jpg") %>
</div>

app/views/shades/design_shades.html.erb
<div class="page-header">
  <h1>Design Shades</h1>
<hr>

<div class="slider">
  <%= image_tag("mountains.jpg") %>
  <%= image_tag("sunglasses.jpg") %>
</div>

app/views/shades/shades_index.html.erb
<div class="page-header">
  <h1>Shades</h1>
<hr>

<div class="slider">
  <li><%= image_tag("redbull.jpg") %></li>
  <li><%= image_tag("gopro.jpg") %></li>
</div>

app/views/shades/sports_shades.html.erb
<div class="page-header">
  <h1>Sports Shades</h1>
<hr>

<div class="slider">
  <%= image_tag("broncos.jpg") %>
  <%= image_tag("CU.jpg") %>
  <%= image_tag("yankees.jpg") %>
</div>

app/views/static_pages/business_info.html.haml
.page-header
  %h1 Information for Businesses

app/views/static_pages/contact_us.html.haml
.page-header
  %h1 Contact Us

.row
  %center
    .well.col-md-4.col-md-offset-4
      %strong
        %u
          %p Eazy Shade
        %p Phone # 970-977-7227

app/views/static_pages/index.html.haml
.page-header
  %h1 Welcome!

%h4 Your source for the best windshield sun shades available!

.well
  %center
    %p= image_tag("eazy_shade2_800px.jpg")

    %table
      %td.col-md-3
        %p= image_tag("temps2_250.jpg")
      %td.col-md-6
        %strong
          Eazy Shade is a marketing tool that lets your customers do your marketing for you while keeping their |
          car cool! Designed and developed by "not and engineer" Bobby Gibbs, the Eazy Shade provides thousands |
          of views by potential clients for a fraction of the price of traditional advertising. Eazy Shade is a |
          unique universal retractable windshield sunshade which can be imprinted with your logo, your slogan or |
          anything else you desire. What sets Eazy Shade apart is that it can be semi-permanently affixed to your |
          windshield yet can be easily moved to other vehicles. |
      %td.col-md-3
        %p= image_tag("temps5_250.jpg")








    -# %p http://www.kten.com/story/14907911/car-interiors-can-exceede-temperatures-of-150-degrees-during-summer
    -# %p http://gizmodo.com/how-hot-does-it-get-inside-a-parked-car-spoiler-so-f-654302290

app/views/static_pages/purchase.html.haml
.page-header
  %h1 Buy EzayShade

blah blah blah